name: Node Github CI

on:
  push:
    branches:
      - master

jobs:
  Build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install
      env:
        CI: true

  deploy:
    needs: [Build]
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy node app - DEV
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_1 }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /opt/nodejs-mysql-crud
          sudo git pull origin master
          sudo npm install 
          sudo pm2 restart node-app
          
    - name: SSH and deploy node app - STAGING
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_2 }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /opt/nodejs-mysql-crud
          sudo git pull origin master
          sudo npm install
          sudo pm2 restart node-app
